# Generated by Django 4.0.5 on 2022-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media/'),
        ),
    ]
