# Generated by Django 4.0.5 on 2022-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('userA', models.CharField(max_length=150)),
                ('userB', models.CharField(max_length=150)),
            ],
        ),
    ]
